$background = 130d09
$onBackground = f7e1d4
$surface = 130d09
$surfaceDim = 130d09
$surfaceBright = 362a21
$surfaceContainerLowest = 000000
$surfaceContainerLow = 19120c
$surfaceContainer = 211811
$surfaceContainerHigh = 281e16
$surfaceContainerHighest = 2f231b
$onSurface = f7e1d4
$surfaceVariant = 2f231b
$onSurfaceVariant = baa79b
$outline = 837267
$outlineVariant = 53453b
$inverseSurface = fff8f5
$inverseOnSurface = 5c534d
$shadow = 000000
$scrim = 000000
$surfaceTint = f3bb91
$primary = f3bb91
$primaryDim = e4ae84
$onPrimary = 5c3817
$primaryContainer = 714928
$onPrimaryContainer = ffddc5
$inversePrimary = 805633
$primaryFixed = ffc69b
$primaryFixedDim = f0b88e
$onPrimaryFixed = 4e2c0c
$onPrimaryFixedVariant = 6f4826
$secondary = e3c0a6
$secondaryDim = d5b299
$onSecondary = 533b28
$secondaryContainer = 4e3624
$onSecondaryContainer = dcb89f
$secondaryFixed = ffdcc3
$secondaryFixedDim = f2cdb3
$onSecondaryFixed = 523a27
$onSecondaryFixedVariant = 715641
$tertiary = fff9e4
$tertiaryDim = ede5a0
$onTertiary = 666029
$tertiaryContainer = f6eda8
$onTertiaryContainer = 5d5822
$tertiaryFixed = fbf3ad
$tertiaryFixedDim = ede5a0
$onTertiaryFixed = 4e4914
$onTertiaryFixedVariant = 6b662e
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 9b6d48
$secondaryPaletteKeyColor = 8f715b
$tertiaryPaletteKeyColor = 7f793f
$neutralPaletteKeyColor = 7f756e
$neutralVariantPaletteKeyColor = 847468
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 9b6d48
$secondary_paletteKeyColor = 8f715b
$tertiary_paletteKeyColor = 7f793f
$neutral_paletteKeyColor = 7f756e
$neutral_variant_paletteKeyColor = 847468
$term0 = 353433
$term1 = e57000
$term2 = ffc078
$term3 = ffe0c8
$term4 = b9ab66
$term5 = ee9466
$term6 = f7c06e
$term7 = ecd4c1
$term8 = b29f92
$term9 = ff892f
$term10 = ffd6ab
$term11 = fff2e9
$term12 = d8bd92
$term13 = fdac81
$term14 = ffd49c
$term15 = ffffff
$rosewater = ffeee6
$flamingo = fedbc8
$pink = ffd4c3
$mauve = ffac92
$red = ff9b62
$maroon = f6ae86
$peach = ffc193
$yellow = ffeee2
$green = ffdaa9
$teal = ffdb94
$sky = e1df87
$sapphire = b3d27e
$blue = ffa2bd
$lavender = ffbcbb
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cd6138
$kvisitedSelection = cc6136
$knegative = db6600
$knegativeSelection = d96800
$kneutral = ff8d23
$kneutralSelection = ff8d19
$kpositive = e39b00
$kpositiveSelection = e19c00
$text = f7e1d4
$subtext1 = baa79b
$subtext0 = 837267
$overlay2 = 73645a
$overlay1 = 62544c
$overlay0 = 53473f
$surface2 = 433932
$surface1 = 342b25
$surface0 = 241c17
$base = 130d09
$mantle = 130d09
$crust = 120c09
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
