$primary_paletteKeyColor = 957125
$secondary_paletteKeyColor = 867556
$tertiary_paletteKeyColor = 647e5c
$neutral_paletteKeyColor = 7e766b
$neutral_variant_paletteKeyColor = 7f7667
$background = 17130b
$onBackground = ebe1d4
$surface = 17130b
$surfaceDim = 17130b
$surfaceBright = 3e382f
$surfaceContainerLowest = 120e07
$surfaceContainerLow = 201b13
$surfaceContainer = 241f17
$surfaceContainerHigh = 2e2921
$surfaceContainerHighest = 3a342b
$onSurface = ebe1d4
$surfaceVariant = 4e4639
$onSurfaceVariant = d1c5b4
$inverseSurface = ebe1d4
$inverseOnSurface = 353027
$outline = 9a8f80
$outlineVariant = 4e4639
$shadow = 000000
$scrim = 000000
$surfaceTint = ecc06c
$primary = ecc06c
$onPrimary = 412d00
$primaryContainer = 5d4200
$onPrimaryContainer = ffdea4
$inversePrimary = 79590c
$secondary = d9c4a0
$onSecondary = 3b2e15
$secondaryContainer = 56472c
$onSecondaryContainer = f6e0bb
$tertiary = b2cfa7
$onTertiary = 1f361a
$tertiaryContainer = 7d9874
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffdea4
$primaryFixedDim = ecc06c
$onPrimaryFixed = 261900
$onPrimaryFixedVariant = 5d4200
$secondaryFixed = f6e0bb
$secondaryFixedDim = d9c4a0
$onSecondaryFixed = 251a04
$onSecondaryFixedVariant = 53452a
$tertiaryFixed = ceebc2
$tertiaryFixedDim = b2cfa7
$onTertiaryFixed = 092007
$onTertiaryFixedVariant = 354d2f
$term0 = 353433
$term1 = c98100
$term2 = f6c542
$term3 = ffe2b3
$term4 = b3ad69
$term5 = e39b4d
$term6 = e1c86e
$term7 = e6d6bf
$term8 = aea18f
$term9 = e99700
$term10 = ffd97d
$term11 = fff2e2
$term12 = cbc193
$term13 = f2b26e
$term14 = f8d973
$term15 = ffffff
$rosewater = feefe1
$flamingo = f9ddc1
$pink = ffd5b2
$mauve = ffad7f
$red = f1a347
$maroon = ecb476
$peach = f6c680
$yellow = ffefd7
$green = fbde76
$teal = eee18c
$sky = e1df87
$sapphire = b3d27e
$blue = 75cf9d
$lavender = ffbcbb
$klink = 559652
$klinkSelection = 559652
$kvisited = c26a00
$kvisitedSelection = c26a00
$knegative = bf7800
$knegativeSelection = bf7800
$kneutral = e59c00
$kneutralSelection = e59c00
$kpositive = c6a700
$kpositiveSelection = c6a700
$text = ebe1d4
$subtext1 = d1c5b4
$subtext0 = 9a8f80
$overlay2 = 867c6e
$overlay1 = 72695c
$overlay0 = 60584c
$surface2 = 4e473c
$surface1 = 3d372c
$surface0 = 2a251c
$base = 17130b
$mantle = 17130b
$crust = 16120a
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
